### ISSUE TITLE
real-time clock SVG logo

### ISSUE THREAD

**Issue by strdr4605** [pebble-dev/pebble-dev.github.io#46]
I was thinking about converting logo SVG into a real-time clock. In plan is to change SVG directly with CSS and JS. If you are ok with that, I can try to do it (first time doing and not sure if it will succeed).

**Comment by ishotjr** [comment]
@strdr4605 that sounds insanely brilliant - I approve! 😍 👍 ⌚️ 🔄

**Comment by strdr4605** [comment]
I will look for some tutorials (to see if it's possible and how hard is it) and will try by next week.
