### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by ishotjr** [pebble-dev/pebble-dev.github.io#53]
At present we lack easy navigation to official Rebble social media and related outlets - it would be incredibly handy if these were easily reachable from the site:

* [Twitter](https://twitter.com/pebble_dev)
* [Facebook](https://www.facebook.com/RebbleAlliance/)
* [Discord](https://discordapp.com/invite/aRUAYFN)
* [Mailing list](https://ishotjr.us14.list-manage.com/subscribe/post?u=602157eb0bbaa9eb99f18f82a&id=1651ac902e)

*@potatofi I'm perhaps looking at you if you want to create really cool Rebble-y social media icons for us...!* 💖

**Comment by PotatoFi** [comment]
Hey @ishotjr! What do you think of these? Depending on how big or small the buttons needs to be, we could make the lines thinner. Let me know how what the dimensions should be, or if you want to make any changes. 

![Twitter](https://user-images.githubusercontent.com/19558338/57054985-5aa08500-6c55-11e9-8a86-07658292ea2a.png)
![Facebook](https://user-images.githubusercontent.com/19558338/57054987-5d02df00-6c55-11e9-913b-474f840441a2.png)
![Discord](https://user-images.githubusercontent.com/19558338/57054989-5ecca280-6c55-11e9-8ead-10623d8386c4.png)
![Email](https://user-images.githubusercontent.com/19558338/57054990-5ffdcf80-6c55-11e9-91af-0b01ee92589e.png)

**Comment by ishotjr** [comment]
@PotatoFi these are just astonishing! ❣️ 😍 ❣️ 😍 ❣️ 😍 ❣️ 😍 ❣️ 

I'm not sure whether the best place for them is the header:

![image](https://user-images.githubusercontent.com/1594827/57055745-4e272700-6c6b-11e9-8c13-062bbe081ec4.png)

or the footer (excuse my crude mockups):

![image](https://user-images.githubusercontent.com/1594827/57056105-3b622180-6c6e-11e9-82fd-2e182f7f28c8.png)

Would you be able to provide something suitable to either (e.g. transparent or something within the existing palette that suits both?)?  Again, I can't get over how fantastic these are - thank you so much!!! :bowtie: 💞

**Comment by PotatoFi** [comment]
@ishotjr How about white lines and a transparent fill (it's here, you just can't see it)?

![Twitter Transparent](https://user-images.githubusercontent.com/19558338/57089272-55791f80-6cc1-11e9-972f-d1f9bf1cf470.png)

**Comment by sGerli** [comment]
I think they look better on the footer. In my opinion, the menu is too crowded.

**Comment by PotatoFi** [comment]
Let me know if you guys need me to take any more action on this. 👍
