### ISSUE TITLE
Older posts should be navigable

### ISSUE THREAD

**Issue by ishotjr** [pebble-dev/pebble-dev.github.io#54]
At present, the home page is limited to 5 posts:

https://github.com/pebble-dev/pebble-dev.github.io/blob/0ddb5801a82819d556a66e2a563dfb3635e7342d/index.html#L9

which results in older posts disappearing...forever! 😅   It would be lovely if [all this classic content](https://github.com/pebble-dev/pebble-dev.github.io/tree/master/_posts) were more easily available via some kind of archive list or other mechanism! :bowtie:

**Comment by ja-besse** [comment]
But should the blog stay at the home page? That was great while people waited for RWS to be available.
I vote for moving to /blog (where, of course, all blog entries should be visible).
/ should have a generic description of the product (RWS) and maybe the company (the Rebble Alliance) (and the mentioned social icons).

**Comment by sGerli** [comment]
I agree with @ja-besse , the home should be more like a product description and maybe a last 1 or 2 blog post excerpts at the bottom.

**Comment by ishotjr** [comment]
@ja-besse @sGerli very cool - I've created a new issue to explore this idea, since this feels quite a bit further off than a simple archived posts list:

https://github.com/pebble-dev/pebble-dev.github.io/issues/56

❣️

**Comment by sGerli** [comment]
I'm currently working on this, I will submit a PR when it's ready.

**Comment by ishotjr** [comment]
@sGerli you could toss a WIP PR up too to help make your claim clear... ❤️

**Comment by ishotjr** [comment]
*closed by #59*
