### ISSUE TITLE
Blog post author attribution

### ISSUE THREAD

**Issue by ishotjr** [pebble-dev/pebble-dev.github.io#55]
While my content is probably fairly recognizable from the extreme overuse of emojis 😅 💭 ❤️ 🚀 :bowtie:, occasionally other authors contribute content, such as @Katharine's [two](https://github.com/pebble-dev/pebble-dev.github.io/pull/34) [posts](https://github.com/pebble-dev/pebble-dev.github.io/pull/40), so it would be nice to attribute each post to the correct author.  Preferably, the solution would incorporate our [`team` collection](https://github.com/pebble-dev/pebble-dev.github.io/blob/master/_data/team.yml); see also [Jekyll docs](https://jekyllrb.com/docs/step-by-step/09-collections/) for more info on how this might be accomplished. 💖

**Comment by Willow-Systems** [comment]
#77 is now merged, which resolves this issue
