### ISSUE TITLE
Home page refactor

### ISSUE THREAD

**Issue by ishotjr** [pebble-dev/pebble-dev.github.io#56]
Per [comments](https://github.com/pebble-dev/pebble-dev.github.io/issues/54#issuecomment-487828883) [elsewhere](https://github.com/pebble-dev/pebble-dev.github.io/issues/54#issuecomment-488101246), it may be time for the site to evolve from simple blog to a more formal/traditional home page, with the blog relinquishing center stage.  Let's use this issue to explore ideas... :bowtie: 💭

**Comment by ja-besse** [comment]
I'd suggest:
- home: what is Rebble; latest 2-3(?) blog posts
- howto: how to use Rebble, later expanded with how to develop for Rebble (install SDK, create watchfaces)
- faq: common issues (taken from the current /howto#common-issues)
- blog: all blog posts
- about: about the alliance; plans and projects; team members; contact info, link to discord
- my account: the signed in page should also state the used sign in account, and include a sign out button

**Comment by sGerli** [comment]
In the home page I think we should have:
- A phone and pebble mockup.
- A small description.
- A (call to action) `Join Rebble` button.
- Somewhere in there a small pricing table.
- 2-3 latest blog post excerpt.

Probably following that order from top to bottom.

**Comment by sGerli** [comment]
And about the site distribution, I agree with @ja-besse. I think we also need to clean up the team page and define a set of rules to appear in there. And maybe make an honorable mention or contributor section in there for the ones that haven't been as active but at some point have either been influential to the project or have contributed to a repo. But this probably needs a separate issue.

**Comment by ishotjr** [comment]
@sGerli would you be able to mock something up for further discussion with the team? 😍 💭 🎨

**Comment by sGerli** [comment]
Here's a rough preview of the top part of the idea:
![image](https://user-images.githubusercontent.com/3890044/58217425-0753ac80-7cc0-11e9-91e4-dfe6206638a9.png)

**Comment by sGerli** [comment]
Here's a better one, I'm still trying to find a place for the device mockup.
![image](https://user-images.githubusercontent.com/3890044/58218153-243daf00-7cc3-11e9-9e35-74bc209af650.png)

**Comment by sGerli** [comment]
Or maybe without a device mockup.
![localhost_4000_ (1)](https://user-images.githubusercontent.com/3890044/58218713-30c30700-7cc5-11e9-9804-9f985bacb0f0.png)

**Comment by ishotjr** [comment]
@sGerli wow!!! 😍 👍 👍 👍 

@PotatoFi would you be able to provide a "Rebble-stylized" phone graphic? ✨

**Comment by PotatoFi** [comment]
@ishotjr Possibly! But first... any reason why we wouldn't just use a Pixel 3 or iPhone XR mockup? I am 100 percent behind Pebble-stylized iconography, but I'm not totally sure that stylizing an entire smartphone fits here.

But if you'd like to try a Pebble-stylized smartphone, I am more than happy to take a crack at it. My initial ideas would be very similar to what we have above.

**Comment by ishotjr** [comment]
@sGerli does #59 close this or is there more we want to do? :bowtie:

**Comment by sGerli** [comment]
I think it closes it, at least for now.

**Comment by ja-besse** [comment]
👍🏻❤️
