### ISSUE TITLE
howto.md states timeline doesn't work

### ISSUE THREAD

**Issue by CennoxX** [pebble-dev/pebble-dev.github.io#65]
In howto.md there is a line saying
> Timeline doesn't work, so simply tap the arrow in the upper right corner.

This should be changed due to [this](http://rebble.io/2019/07/24/its-timeline-time.html).

**Comment by ishotjr** [comment]
@ja-besse would you like to handle this update? :heart:

**Comment by ja-besse** [comment]
No problem!
